#!/bin/bash

cd ${OPENSHIFT_JETTY_DIR}

CMD="java -Xms384m -Xmx412m -jar start.jar -Djetty.host=$OPENSHIFT_JETTY_IP -Djetty.port=$OPENSHIFT_JETTY_PORT"

nohup $CMD > $OPENSHIFT_JETTY_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid


